name: Build React App and Push to Bucket

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1

jobs:
  build_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      
      - name: Install Dependencies
        run: npm ci

      - name: Create .env.production
        run: |
          echo "VITE_SERVER_URL=${{ secrets.VITE_SERVER_URL }}" >> .env.production

      - name: Build the application
        run: npm run build
      
      - name:  Deploy Build to Bucket
        uses: sai-sharan/aws-s3-sync-action@master
        with: 
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region:  ${{env.AWS_REGION}}
          source: 'dist'
          destination_bucket: ${{ secrets.AWS_S3_BUCKET_NAME  }}
          delete: true
          quiet: false