name: build and push image to ecr

on:
  push:
    braches:
      - main
env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: stride_flow_frontend

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Build, tag and push docker image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
          --build-arg VITE_SERVER_URL=${{ secrets.VITE_SERVER_URL }} \
          -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            ${{ secrets.ECR_LOGIN }}
            cd stride_flow
            sed -i "s|amazonaws.com/stride_flow_frontend:.*|amazonaws.com/stride_flow_frontend:${{ github.sha }}|" docker-compose-prod.yaml
            docker compose -f docker-compose-prod.yaml up -d
